/**
 * Amazon Selection Funnel Filter Metadata
 * Synchronized with ss_search_params.py parameter names.
 */

export const AMZ_FILTER_LABELS: Record<string, string> = {
  // ── 月份 ──
  "month": "月份",
  // ── 销售表现 ──
  "monthly_sales_min": "月销量 ≥",
  "monthly_sales_max": "月销量 ≤",
  "monthly_revenue_min": "月销售额 ≥",
  "monthly_revenue_max": "月销售额 ≤",
  "child_sales_min": "子体销量 ≥",
  "child_sales_max": "子体销量 ≤",
  "sales_growth_min": "月销量增长率 ≥",
  "sales_growth_max": "月销量增长率 ≤",
  "bsr_min": "BSR ≥",
  "bsr_max": "BSR ≤",
  "sub_bsr_min": "小类BSR ≥",
  "sub_bsr_max": "小类BSR ≤",
  "sub_category_only": "只看该子类目排名",
  "bsr_growth_num_min": "BSR增长数 ≥",
  "bsr_growth_num_max": "BSR增长数 ≤",
  "bsr_growth_rate_min": "BSR增长率 ≥",
  "bsr_growth_rate_max": "BSR增长率 ≤",
  // ── 产品信息 ──
  "variants_min": "变体数 ≥",
  "variants_max": "变体数 ≤",
  "price_min": "价格 ≥",
  "price_max": "价格 ≤",
  "qa_min": "Q&A ≥",
  "qa_max": "Q&A ≤",
  "review_count_min": "评分数 ≥",
  "review_count_max": "评分数 ≤",
  "monthly_reviews_min": "月评新增 ≥",
  "monthly_reviews_max": "月评新增 ≤",
  "rating_min": "评分值 ≥",
  "rating_max": "评分值 ≤",
  "review_rate_min": "留评率 ≥",
  "review_rate_max": "留评率 ≤",
  "fba_fee_min": "FBA运费 ≥",
  "fba_fee_max": "FBA运费 ≤",
  "gross_margin_min": "毛利率 ≥",
  "gross_margin_max": "毛利率 ≤",
  "listing_age": "上架时间",
  "lqs_min": "LQS ≥",
  "lqs_max": "LQS ≤",
  "pkg_weight_min": "包装重量 ≥",
  "pkg_weight_max": "包装重量 ≤",
  "pkg_size": "包装尺寸",
  "buyer_shipping_min": "买家运费 ≥",
  "buyer_shipping_max": "买家运费 ≤",
  "low_price": "低价商品",
  // ── 竞品筛选 ──
  "seller_count_min": "卖家数量 ≥",
  "seller_count_max": "卖家数量 ≤",
  "seller_location": "卖家所属地",
  "include_brand": "包含品牌",
  "exclude_brand": "排除品牌",
  "include_seller": "包含卖家",
  "exclude_seller": "排除卖家",
  "exclude_keyword": "排除关键词",
  "include_keyword": "包含关键词",
  "keyword_match": "关键词匹配",
  "fba": "FBA",
  "amz": "AMZ",
  "fbm": "FBM",
  "video": "主图视频",
  "product_tags": "商品标识",
  // ── Phase 2-5 后处理 ──
  "max_seller_reviews": "店铺评价数上限",
  "min_store_listing_count": "店铺最少商品数",
  "max_high_sales_ratio": "成熟产品占比上限",
  "high_sales_threshold": "高销量阈值",
  "max_launch_reviews": "上架时评论数限制",
  "max_3m_reviews": "3个月后评论上限",
  "min_3m_reviews": "3个月后评论下限",
  "review_jump_threshold": "评论跳涨阈值",
  "max_review_jumps": "允许评论跳涨次数",
  "max_min_ppc": "核心词最低竞价上限",
  "max_comp_reviews": "首页对标评价数限制",
};
